### PR TITLE
fix: select return undefined

### LINKED ISSUE #12: select returns undefined
The select prompt currently returns `undefined` instead of the selected options value.

```typescript
const projectType = await select({
  message: "TypeScript or JavaScript?",
  options: [
    { value: "ts", label: "TypeScript", hint: "recommended" },
    { value: "js", label: "JavaScript" },
  ],
});

console.log(projectType) // undefined
```

### PR DESCRIPTION
**Pull request by fz6m**
fix #12

### CODE REVIEW

File: packages/core/src/prompts/select.ts [hunk 1]
```diff
@@ -12,25 +12,29 @@ export default class SelectPrompt<T extends { value: any }> extends Prompt {
...
             switch (key) {
                 case 'left': 
                 case 'up': 
-                    return this.cursor = this.cursor === 0 ? this.options.length - 1 : this.cursor - 1;
+                    this.cursor = this.cursor === 0 ? this.options.length - 1 : this.cursor - 1;
+                    break;
                 case 'down': 
                 case 'right':
-                    return this.cursor = this.cursor === this.options.length - 1 ? 0 : this.cursor + 1;
+                    this.cursor = this.cursor === this.options.length - 1 ? 0 : this.cursor + 1;
```
Comment (natemoo-re) [inline packages/core/src/prompts/select.ts:35]:
```suggestion
                    this.cursor = this.cursor === this.options.length - 1 ? 0 : this.cursor + 1;
                    break;
```

**Comment by natemoo-re** [comment]
Thanks for the PR! I really appreciate it.
